New counters and customize names
bobloy/Fox-V3 pull request #163
Opened 2020-12-03 03:21 UTC by ASSASSIN0831

2020-12-03 03:23 UTC, ASSASSIN0831 commented on infochannel/infochannel.py
> -
I added that to help during debugging and forgot to delete it at the end. Whoops

2020-12-03 03:28 UTC, ASSASSIN0831 commented
I was wondering if there should be some sort of hardcoded limit to the amount of role counters you can add. I feel like with too many, you could run into a rate limit issue

2020-12-03 14:10 UTC, bobloy requested changes
Firstly, thank you so much for this work. I greatly appreciate it, and I'm sure the users of this cog will too.

I'm starting the review on this, but there are a few issue right off the bat.

The first and easiest to fix is this should follow the `black` formatting guidelines with line length of 99.
I recommend `pip install black` then `black <file_path> -l 99` to apply these formatting changes.

Secondly, your fear about rate limits are correct. Due to the number of events this is listening to, it's likely better off ignoring the events entirely and running on a schedule instead.

With your permission, I'd like to take this PR and make the necessary modifications myself.

2020-12-03 19:03 UTC, ASSASSIN0831 commented
I ran the black formatting command you gave and have now committed that change. Also, with the change to get rid of the listeners, remember to not entirely get rid of the on_guild_role_delete listener because it's used to delete the role's channel if the role gets deleted.

2020-12-08 16:06 UTC, bobloy commented
I've applied the rate-limiting features I was interested in. Ended up using listeners still.

Also refactor much of the code, so this is now a complete rewrite.

Incompatible with older versions, so channels will need to be deleted and re-setup.

2020-12-08 16:09 UTC, merged